### ISSUE TITLE
MultiMerch Products list not showing on opencart

### ISSUE THREAD

**Issue by blacklionxs** [multimerch/multimerch#53]
Hi, 
I have a probleme with my multimerch opencart 2.0.1.1 ; products list not showing for the seller (" Processing ... " )

it was working before but now stopped, i've added lots of scripts and extensions i can't find which is the problem, i've uplodded files of multimerch again by ftp and re-installed the Module but nothing changed :(

how can i solve the problem ?
![2015-02-02_02-25-39](https://cloud.githubusercontent.com/assets/10803075/6020158/e0b39258-aba8-11e4-83c9-42cb92f59686.png)

**Comment by ffctcc** [comment]
Hi,

What version of MultiMerch exactly are you using (you can find it in system/library/msloader.php)? Also, please check the JavaScript console and Net/Requests tab using Chrome Developer Tools or Firebug. This should give you the exact error that's causing it.

I assume you haven't upgraded to MultiMerch 7.0.1.7. We've fixed a bug with DataTables that was causing this in 7.0.1.7.

Martin

**Comment by blacklionxs** [comment]
Hi,

Thanks to reply, 
Yes i'm using 7.0.1.6 i think
This is what javascript console show : 

jquery.dataTables.min.js:94 Uncaught Error: DataTables warning (table id = 'list-products'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error

and if i want to upgrade version, have i only replace by ftp or i have to delete the oldest version ? :)

**Comment by ffctcc** [comment]
You can simply install the new version on top of the existing one. Just make sure you don't overwrite your previous changes.

**Comment by blacklionxs** [comment]
i did what you told me, but it still show "Processing..." :(

**Comment by ffctcc** [comment]
Can you please provide me with a link and a demo account where this is happening? You can also mail the accesses to support@multimerch.com

**Comment by blacklionxs** [comment]
@ffctcc Hi, i've found the problem it was about automatic_seo_url extension, i've deleted the file and the product list worked :) 
how can i set automatic seo to work with multimerch ?

thanks for your support

:)

**Comment by ffctcc** [comment]
Like I mentioned in the email, at the moment automatic seo extensions aren't supported. The best bet would be to either contact the extension developer or create a thread on MM forums so that we can discuss this.
